import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import Link from 'next/link'
import { getPostList } from '../lib/posts'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const postList = await getPostList();
  // console.log("heyyy", postList)
  // const post = JSON.parse(postData.value)
  return {
    props: {
      postList,
    }
  }
}

const Home: NextPage = ({ postList }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {"Welcome to di-uni's Blog!"}
        </h1>

        <p className={styles.description}>
        </p>
        <div className={styles.grid}>
          {postList ? postList.map((title: any) => {
              return (
                  <Link key={title} href={`/posts/${title}`}>
                      <a className={styles.card}>
                          <h2>{title} &rarr;</h2>
                          <p>Descriptions..... </p>
                      </a>
                  </Link>
              )})
          : null}
        </div>
      </main>
    </div>
  )
}

export default Home
