import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import Link from 'next/link'
import useSWR, { SWRConfig } from 'swr'
import { getAllPostIds, getPostData, getPostList } from '../lib/posts'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const postList = await getPostList();
  const postIds = getAllPostIds();

  const postData = {};
  await Promise.all(postIds.map(async item => {
    const postContent = await getPostData(item.params.id);
    Object.assign(postData, postContent);
  }))
  
  return {
    props: {
      fallback: {
        'postList': postList,
        'postData': JSON.stringify(postData),
      }
    }
  }
}

const PostList = () => {
  const { data: postList } = useSWR('postList');
  const { data: postData } = useSWR('postData');
  const postDataObj = JSON.parse(postData);

  return (
    <div className={styles.grid}>
      {postList ? postList.map((title: string) => {
          return (
              <Link key={title} href={{
                pathname: `/posts/${title}`,
                query: {[title]: postDataObj[title]}
                }}>
                  <a className={styles.card}>
                      <h2>{title} &rarr;</h2>
                      <p>Descriptions..... </p>
                  </a>
              </Link>
          )})
      : null}
    </div>)
}

const Home: NextPage = ({ fallback }: any) => {
  return (
    <SWRConfig value={{ fallback }}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            {"Welcome to di-uni's Blog!"}
          </h1>

          <p className={styles.description}>
          </p>

          <PostList />
        </main>
      </div>
    </SWRConfig>
  )
}

export default Home
